import React, { useEffect, useRef } from 'react';

interface TradingViewWidgetProps {
  symbol?: string; // TradingView symbol, e.g. 'OANDA:XAUUSD'
  onClose: () => void;
}

/**
 * Embeds TradingView's official free "Advanced Chart" widget.
 * This is REAL market data straight from TradingView -- not something
 * this app generates. Free, no API key required, officially supported
 * embed: https://www.tradingview.com/widget/advanced-chart/
 */
export const TradingViewWidget: React.FC<TradingViewWidgetProps> = ({
  symbol = 'OANDA:XAUUSD',
  onClose
}) => {
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!containerRef.current) return;
    containerRef.current.innerHTML = '';

    const widgetDiv = document.createElement('div');
    widgetDiv.className = 'tradingview-widget-container__widget';
    widgetDiv.style.height = '100%';
    widgetDiv.style.width = '100%';
    containerRef.current.appendChild(widgetDiv);

    const script = document.createElement('script');
    script.src = 'https://s3.tradingview.com/external-embedding/embed-widget-advanced-chart.js';
    script.type = 'text/javascript';
    script.async = true;
    script.innerHTML = JSON.stringify({
      autosize: true,
      symbol,
      interval: '5',
      timezone: 'Etc/UTC',
      theme: 'dark',
      style: '1',
      locale: 'en',
      enable_publishing: false,
      allow_symbol_change: true,
      calendar: false,
      support_host: 'https://www.tradingview.com'
    });
    containerRef.current.appendChild(script);
  }, [symbol]);

  return (
    <div className="absolute inset-0 z-40 bg-[#0A0C10] flex flex-col">
      <div className="flex items-center justify-between px-4 py-2 border-b border-[#232830] bg-[#12151b]">
        <span className="text-xs font-mono text-[#7C8592]">
          Live TradingView chart — real market data, not generated by this app
        </span>
        <button
          onClick={onClose}
          className="text-xs font-mono px-3 py-1 rounded bg-[#171B22] text-[#e2e2e8] hover:opacity-80"
        >
          Back to terminal chart
        </button>
      </div>
      <div className="tradingview-widget-container flex-1" ref={containerRef} style={{ height: '100%', width: '100%' }} />
    </div>
  );
};
